

filename_fieldname = {
	
	"SGRLIST": 				['SGR CODE','SILVICULTURAL SYSTEM','TARGET FU','TARGET YIELD','SITE PREPARATION','REGENERATION','TENDING'],
	"PROJECTEDFOREST": 		['FOREST UNIT','AGE CLASS','TERM','AREA'],
	"PROJECTEDHARVESTAREA":	['FOREST UNIT','TERM','AREA'],
	"PROJECTEDHARVESTVOLUME":['SPECIES','PRODUCT','TERM','VOLUME'],
	"PROJECTEDSTRUCTURE": 	['LANDSCAPE GUIDE INDICATOR','TERM','AREA'],


}


